# Generated by Django 3.0.1 on 2020-01-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_pic', models.ImageField(null=True, upload_to='')),
                ('product_name', models.TextField()),
                ('product_price', models.IntegerField(max_length=50)),
                ('product_model', models.TextField()),
                ('product_category', models.TextField()),
                ('product_gender', models.TextField(null=True)),
                ('product_details', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_email', models.TextField()),
                ('user_address', models.TextField(null=True)),
                ('user_gender', models.TextField()),
                ('user_age', models.IntegerField(max_length=50)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.TextField()),
                ('payment_type', models.TextField()),
                ('user_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.TextField()),
                ('order_type', models.TextField()),
                ('order_date', models.IntegerField(max_length=50)),
                ('user_order', models.ManyToManyField(related_name='orders', to='products.User')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_name', models.TextField()),
                ('invoice_number', models.IntegerField(max_length=50)),
                ('user_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.User')),
            ],
        ),
    ]
