# Generated by Django 3.0.1 on 2020-01-24 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='users_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='user_payment',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='products.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user_order',
            field=models.ManyToManyField(related_name='orders', to='products.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.TextField(null=True),
        ),
    ]
